AUGMENTATIONS:
  EVAL:
    CROP_PCT: null
  TRAIN:
    AUTO_AUGMENT_POLICY: null
    COLOR_JITTER_PROB: 0.4
    DISABLE: false
    HFLIP_PROB: 0.5
    INTERPOLATION_MODE: bilinear
    RANDOM_ERASE_COUNT: 1
    RANDOM_ERASE_MODE: const
    RANDOM_ERASE_PROB: 0.0
    VFLIP_PROB: 0.0
BACKEND:
  CUDNN_BENCHMARK: true
  DATALOADER_PIN_MEMORY: true
  DATASET_DOWNLOAD_FOLDER: ./dataset
  SCALE_LEARNING_RATE: true
BAG_OF_TRICKS:
  EMA:
    EMA_DECAY: 0.99
    EMA_UPDATE_INTERVAL: 5
    DO_EMA: false
  GRADIENT_CLIPPING:
    DO_GRADIENT_CLIPPING: true
    METHOD: norm
    NORM_MAX: 5.0
    NORM_TYPE: 2
    VALUE: 5.0
  MIXUP_CUTMIX:
    CUTMIX_ALPHA: 0.1
    CUTMIX_MINMAX: null
    DO_CUTMIX: true
    MIXUP_ALPHA: 0.1
    MIXUP_MODE: batch
    MIXUP_PROB: 1.0
    SWITCH_PROB: 0.5
  STOCHASTIC_DEPTH:
    DROP_PATH_RATE: 0.05
DATA:
  DATASET: torchvision_cifar10
  PRE_SPLIT_TRAIN_VAL: false
  PIXEL_MEAN:
  - 0.485
  - 0.456
  - 0.406
  PIXEL_STD:
  - 0.229
  - 0.224
  - 0.225
  SPLIT_EVAL: 0.2
  SPLIT_TRAIN: 0.8
DATALOADER:
  DO_GRADIENT_ACCUMULATION: false
  GRADIENT_ACCUMULATION_STEPS: 16
  NUM_WORKERS: 4
  PER_STEP_BATCH_SIZE: 64
EVALUATION:
  METRIC: accuracy
  SELECT_EMA_MODEL: false
  TRACK_EMA: false
EXPERIMENT:
  DEVICE: cpu
  SEED: 3407
  WORKDIR: ./workdir_quickstart_cifar10
LOGGING:
  DO_TENSORBOARD_LOGGING: true
  LOGGING_ITER_INTERVAL: 10
LOSS_FUNCTION:
  LABEL_SMOOTHING: 0.1
LR_SCHEDULER:
  LR_MULTIPLICATIVE_FACTOR: 0.95
  MILESTONES:
  - 60
  - 80
  MIN_LR: 1.0e-06
  TYPE: CosineAnnealingWithWarmup
  UPDATE_PERIOD: 5
  WARMUP_STEPS: 5
MODEL:
  DROPOUT_RATE: 0.0
  INPUT_SIZE: 32
  NAME: timm_convnext_atto
  USE_PRETRAIN: true # For comapring against imagenette benchmarks, pretraining should not be used.
OPTIMIZER:
  BASE_LEARNING_RATE: 0.05
  BETAS:
  - 0.9
  - 0.999
  EPS: 1.0e-04
  MOMENTUM: 0.9
  TYPE: AdamW
  WEIGHT_DECAY: 0.001
TRAINING:
  EPOCHS: 20
  USE_AMP: true

